export interface Person {
  givenName: string;
  surName: string;
  age: number;
  email: string;
  address: string;
}

export interface EPerson {
  givenName: string;
  surName: string;
  age: string;
  email: string;
  education: string;
}

export const ManyPerson: EPerson[] = [
  {
    givenName: 'Alyssa',
    surName: 'Clark',
    age: '51',
    email: 'a_clark@outlook.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Andrew',
    surName: 'Russell',
    age: '62',
    email: 'arussell@aol.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Alexander',
    surName: 'Rivera',
    age: '35',
    email: 'alexander_andrew_rivera@gmail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Amber',
    surName: 'Roberts',
    age: '19',
    email: 'aroberts@ymail.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Isaac',
    surName: 'Butler',
    age: '29',
    email: 'icbutler29@outlook.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Aiden',
    surName: 'Turner',
    age: '22',
    email: 'aiden_turner50@gmail.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Claire',
    surName: 'Long',
    age: '55',
    email: 'clairem@aol.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Emma',
    surName: 'Lopez',
    age: '57',
    email: 'e_lopez@aol.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Nicole',
    surName: 'Hughes',
    age: '62',
    email: 'nicolehughes@rocketmail.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Austin',
    surName: 'Torres',
    age: '40',
    email: 'a.torres@rocketmail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Aiden',
    surName: 'Phillips',
    age: '55',
    email: 'aidenephillips@gmail.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Thomas',
    surName: 'Nelson',
    age: '42',
    email: 't_nelson@outlook.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Eleanor',
    surName: 'Taylor',
    age: '51',
    email: 'eleanor_lynn_taylor@outlook.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Kyle',
    surName: 'Allen',
    age: '46',
    email: 'k_allen@outlook.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Layla',
    surName: 'Nelson',
    age: '31',
    email: 'l.nelson@ymail.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Eric',
    surName: 'Allen',
    age: '52',
    email: 'eric.j.allen@yahoo.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Ethan',
    surName: 'Lopez',
    age: '69',
    email: 'ethan@rocketmail.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Natalie',
    surName: 'James',
    age: '64',
    email: 'nataliekjames2@gmail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Dylan',
    surName: 'Davis',
    age: '43',
    email: 'dylanmdavis@live.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Taylor',
    surName: 'Roberts',
    age: '72',
    email: 't.d@rocketmail.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Patrick',
    surName: 'Henderson',
    age: '35',
    email: 'patrickroberthenderson@yahoo.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Tyler',
    surName: 'Williams',
    age: '56',
    email: 'tm24@aol.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Samuel',
    surName: 'Taylor',
    age: '48',
    email: 'samueltaylor@ymail.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Taylor',
    surName: 'Henderson',
    age: '46',
    email: 'taylorhenderson@hotmail.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Matthew',
    surName: 'Clark',
    age: '26',
    email: 'matthew_lee_clark@ymail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Tyler',
    surName: 'Jackson',
    age: '61',
    email: 'tylerjackson@ymail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Andrew',
    surName: 'Roberts',
    age: '75',
    email: 'andrew_roberts@yahoo.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Samuel',
    surName: 'Moore',
    age: '23',
    email: 's.e.moore47@ymail.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Dylan',
    surName: 'Davis',
    age: '46',
    email: 'dmdavis@ymail.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Sebastian',
    surName: 'Lewis',
    age: '51',
    email: 'sebastian.lewis@live.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Sarah',
    surName: 'Price',
    age: '46',
    email: 's.price@outlook.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Sophia',
    surName: 'Russell',
    age: '33',
    email: 'sophia@ymail.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Sarah',
    surName: 'Jenkins',
    age: '40',
    email: 's_jenkins@gmail.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Charles',
    surName: 'White',
    age: '71',
    email: 'c.white39@live.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Zachary',
    surName: 'Gonzales',
    age: '39',
    email: 'zacharygonzales@ymail.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Sofia',
    surName: 'Barnes',
    age: '24',
    email: 'sbarnes@live.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Andrew',
    surName: 'Ward',
    age: '70',
    email: 'andrew_ward@outlook.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Samuel',
    surName: 'Coleman',
    age: '76',
    email: 'samuelalancoleman@live.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Jose',
    surName: 'Taylor',
    age: '77',
    email: 'j_m@rocketmail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Adam',
    surName: 'Taylor',
    age: '70',
    email: 'ataylor@yahoo.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Sarah',
    surName: 'White',
    age: '55',
    email: 'sarah.faith.white@rocketmail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Jose',
    surName: 'Campbell',
    age: '20',
    email: 'jose.campbell@ymail.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Ava',
    surName: 'Wilson',
    age: '33',
    email: 'avadawn@outlook.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Isabella',
    surName: 'Wood',
    age: '71',
    email: 'i.wood@outlook.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Kayla',
    surName: 'Parker',
    age: '68',
    email: 'k.parker@ymail.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Michael',
    surName: 'Turner',
    age: '36',
    email: 'michael_david_turner46@outlook.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Anthony',
    surName: 'Powell',
    age: '62',
    email: 'a.powell@live.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Rebecca',
    surName: 'Hughes',
    age: '18',
    email: 'rhughes49@aol.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Tiffany',
    surName: 'Campbell',
    age: '19',
    email: 'tiffany_campbell@aol.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Michael',
    surName: 'Robinson',
    age: '34',
    email: 'm_d_robinson@gmail.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Richard',
    surName: 'Foster',
    age: '39',
    email: 'richard_r@ymail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Courtney',
    surName: 'Henderson',
    age: '57',
    email: 'crhenderson20@aol.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Sara',
    surName: 'Cook',
    age: '68',
    email: 's_cook@ymail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Oliver',
    surName: 'Ward',
    age: '33',
    email: 'oliver@gmail.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Taylor',
    surName: 'Bell',
    age: '24',
    email: 'taylorjanebell@aol.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Victoria',
    surName: 'Anderson',
    age: '23',
    email: 'victoriar8@ymail.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Anna',
    surName: 'Morris',
    age: '19',
    email: 'a_i_morris@ymail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Taylor',
    surName: 'Lee',
    age: '71',
    email: 'taylorllee@rocketmail.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Emma',
    surName: 'Wood',
    age: '70',
    email: 'emmawood@yahoo.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Michelle',
    surName: 'Harris',
    age: '69',
    email: 'm.l.harris@yahoo.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Jasmine',
    surName: 'Sanders',
    age: '37',
    email: 'jasminesanders@aol.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Danielle',
    surName: 'Williams',
    age: '75',
    email: 'dlwilliams@gmail.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Elizabeth',
    surName: 'Rogers',
    age: '51',
    email: 'e.l.rogers@aol.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Kayla',
    surName: 'Green',
    age: '31',
    email: 'kmgreen@ymail.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Jack',
    surName: 'Young',
    age: '62',
    email: 'jack.young@rocketmail.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Timothy',
    surName: 'Murphy',
    age: '64',
    email: 't_f_murphy56@aol.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Theodore',
    surName: 'King',
    age: '50',
    email: 't_a_king@rocketmail.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Timothy',
    surName: 'Carter',
    age: '48',
    email: 'tcarter@outlook.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Brianna',
    surName: 'Ramirez',
    age: '51',
    email: 'briannaannramirez@live.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Stephanie',
    surName: 'King',
    age: '27',
    email: 'stephanie_k_king@live.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Layla',
    surName: 'Bennett',
    age: '26',
    email: 'layla_bennett@aol.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Alexandra',
    surName: 'Smith',
    age: '77',
    email: 'amsmith@outlook.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Eleanor',
    surName: 'Murphy',
    age: '47',
    email: 'e.murphy@ymail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Sarah',
    surName: 'Butler',
    age: '54',
    email: 'sabutler@aol.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Stephanie',
    surName: 'Hayes',
    age: '31',
    email: 'stephanie.hayes@gmail.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Jessica',
    surName: 'Rogers',
    age: '65',
    email: 'ja12@aol.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Charles',
    surName: 'Peterson',
    age: '43',
    email: 'charles@live.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Rebecca',
    surName: 'Alexander',
    age: '19',
    email: 'r_m_alexander@aol.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Abigail',
    surName: 'Bryant',
    age: '30',
    email: 'abigail_may@hotmail.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'David',
    surName: 'Watson',
    age: '66',
    email: 'd_s@yahoo.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Amanda',
    surName: 'Evans',
    age: '23',
    email: 'amanda_michelle_evans@ymail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Steven',
    surName: 'Russell',
    age: '21',
    email: 'stevenrussell@rocketmail.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Kyle',
    surName: 'King',
    age: '33',
    email: 'k.m@live.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Audrey',
    surName: 'Walker',
    age: '38',
    email: 'a.walker@ymail.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Richard',
    surName: 'Thomas',
    age: '57',
    email: 'r_thomas@live.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Steven',
    surName: 'Green',
    age: '24',
    email: 's_g_green6@hotmail.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Charles',
    surName: 'Wilson',
    age: '18',
    email: 'charles_michael_wilson66@yahoo.com',
    education: 'Less than high school',
  },
  {
    givenName: 'David',
    surName: 'Russell',
    age: '52',
    email: 'david_russell@yahoo.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Layla',
    surName: 'Collins',
    age: '71',
    email: 'l_m_collins91@rocketmail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Joshua',
    surName: 'Coleman',
    age: '20',
    email: 'jcoleman@live.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Natalie',
    surName: 'Robinson',
    age: '71',
    email: 'natalie@aol.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Daniel',
    surName: 'Jenkins',
    age: '23',
    email: 'd_a@outlook.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Lauren',
    surName: 'Torres',
    age: '24',
    email: 'lauren_r_torres48@hotmail.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Dylan',
    surName: 'Johnson',
    age: '52',
    email: 'd.g.johnson@gmail.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Theodore',
    surName: 'Washington',
    age: '41',
    email: 'theodore97@live.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Theodore',
    surName: 'James',
    age: '21',
    email: 't.e.james@rocketmail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Jack',
    surName: 'Hayes',
    age: '41',
    email: 'jack@hotmail.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Taylor',
    surName: 'Powell',
    age: '68',
    email: 'tr@outlook.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Nathan',
    surName: 'Rodriguez',
    age: '74',
    email: 'nerodriguez@hotmail.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Emma',
    surName: 'Howard',
    age: '32',
    email: 'e.howard@rocketmail.com',
    education: 'Bachelor’s degree',
  },
];
